services:
  redis:
    image: redis:7.4-alpine
    container_name: async-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redisAsyncApi --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
